language: node_js

env:
  - CXX=g++-4.8
os:
  - linux

node_js:
#  - 4
#  - 6
  - 8
  - 9
  - 10

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

sudo: false

before_install:
  - $CXX --version
